/**
 * @format
 */
import 'react-native-gesture-handler';
import React,{Component} from 'react';
import {AppRegistry, Text} from 'react-native';
import App from './src/App';
//import App from './App';
import {name as appName} from './app.json';
import Provider from 'react-redux/lib/components/Provider';
import {PersistGate} from 'redux-persist/integration/react';
import {LoadingPage} from './src/pages/LoadingPage';
import {store, persistor} from './src/redux/store/store';
//import messaging from '@react-native-firebase/messaging';
import PushNotification from 'react-native-push-notification';


// Register background handler
/*
messaging().setBackgroundMessageHandler(async (remoteMessage) => {
    console.log('#--------------------------------------------------Message handled in the background!', remoteMessage);
});
*/


// PushNotification.configure({
//
//     // (optional) Called when Token is generated (iOS and Android)
//     onRegister: function(token) {
//         console.log( 'TOKEN:', token );
//     },
//
//     // (required) Called when a remote or local notification is opened or received
//     onNotification: function(notification) {
//         console.log( 'NOTIFICATION:', notification );
//     },
//
//     // ANDROID ONLY: GCM Sender ID (optional - not required for local notifications, but is need to receive remote push notifications)
//     //senderID: "YOUR GCM SENDER ID",
//
//     // IOS ONLY (optional): default: all - Permissions to register.
//     permissions: {
//         alert: true,
//         badge: true,
//         sound: true
//     },
//
//     // Should the initial notification be popped automatically
//     // default-> true
//     popInitialNotification: true,
//     requestPermissions: true,
// });

// const createPushNotification = () => {
//     console.log('##### ---------------------------------------------------CREATe NOTIFICATION CALLED');
//     PushNotification.localNotification({
//         /* Android Only Properties */
//         channelId: "channel-cooltivar",
//         //id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
//         ticker: "My Notification Ticker", // (optional)
//         //autoCancel: true, // (optional) default: true
//         largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
//         smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
//         bigText: "My big text that will be shown when notification is expanded", // (optional) default: "message" prop
//         subText: "This is a subText", // (optional) default: none
//         color: "red", // (optional) default: system default
//         vibrate: true, // (optional) default: true
//         vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
//         tag: 'some_tag', // (optional) add tag to message
//         group: "group", // (optional) add group to message
//         ongoing: false, // (optional) set whether this is an "ongoing" notification
//         title: "titolo notifica",
//         message: "messaggio notifica Normale"
//     });
//     console.log('##### ---------------------------------------------------CREATe NOTIFICATION FINE');
// };
/*
const callBackTest = function(){
console.log('NOTIFICATION CALLBACK TEST',arguments)
};

setTimeout(()=>{
    PushNotification.getDeliveredNotifications(callBackTest);
    PushNotification.getScheduledLocalNotifications(callBackTest);
    },10000);
*/
// PushNotification.createChannel(
//     {
//         channelId: "channel-cooltivar", // (required)
//         channelName: "My channel", // (required)
//         channelDescription: "A channel to categorise your notifications", // (optional) default: undefined.
//         playSound: false, // (optional) default: true
//         soundName: "default", // (optional) See `soundName` parameter of `localNotification` function
//         importance: 4, // (optional) default: 4. Int value of the Android notification importance
//         vibrate: true, // (optional) default: true. Creates the default vibration patten if true.
//     },
//     (created) => console.log(`Notification createChannel returned '${created}'`) // (optional) callback returns whether the channel was created, false means it already existed.
// );
/*
const createScheduledNotification = ()=>{
    PushNotification.localNotificationSchedule({
        channelId: "channel-cooltivar",
        title: "titolo notifica",
        message: "My SCHEDULED Notification Message", // (required)
        date: new Date(Date.now()+ 15*1000) // in 60 secs
    });
    console.log('##### ---------------------------------------------------CREATe NOTIFICATION SCHED');
};*/
/*
PushNotification.getChannels(function (channel_ids) {
    console.log(channel_ids); // ['channel_id_1']
});*/
//PushNotificationsHandler.requestPermissions();
//createPushNotification();
//createScheduledNotification();


class Root extends Component {
    render() {
        console.log("----------------STORE", store, persistor);
        return (
            <Provider store={store} loading={<Text>Loading...</Text>}>
                <PersistGate persistor={persistor} loading={<Text>Loading...</Text>}>
                    <App />
                </PersistGate>
            </Provider>
        );
    }
}
// <Provider store={store}>
AppRegistry.registerComponent(appName, () => Root);
