export const E_OPENWEATHER_GET_TODAY = "E_OPENWEATHER_GET_TODAY";
export const E_OPENWEATHER_GET_FORECAST = "E_OPENWEATHER_GET_FORECAST";

export const METEO_ENUM = {
    E_OPENWEATHER_GET_TODAY: E_OPENWEATHER_GET_TODAY,
    E_OPENWEATHER_GET_FORECAST: E_OPENWEATHER_GET_FORECAST,
};
