//import messaging from '@react-native-firebase/messaging';
import PushNotification from 'react-native-push-notification';

// Register background handler
/*
messaging().setBackgroundMessageHandler(async (remoteMessage) => {
    console.log('#--------------------------------------------------Message handled in the background!', remoteMessage);
});*/
export const configureNotification = () =>{
    PushNotification.configure({

    // (optional) Called when Token is generated (iOS and Android)
    onRegister: function(token) {
        console.log( 'TOKEN:', token );
    },

    // (required) Called when a remote or local notification is opened or received
    onNotification: function(notification) {
        console.log( 'NOTIFICATION:', notification );
    },

    // ANDROID ONLY: GCM Sender ID (optional - not required for local notifications, but is need to receive remote push notifications)
    //senderID: "YOUR GCM SENDER ID",

    // IOS ONLY (optional): default: all - Permissions to register.
    /*permissions: {
        alert: true,
        badge: true,
        sound: true
    },*/

    // Should the initial notification be popped automatically
    // default-> true
    popInitialNotification: true,

    /**
     * (optional) default: true
     * - Specified if permissions (ios) and token (android and ios) will requested or not,
     * - if not, you must call PushNotificationsHandler.requestPermissions() later
     */
    requestPermissions: true,
});
};



/*
const callBackTest = function(){
    console.log('NOTIFICATION CALLBACK TEST',arguments)
};

setTimeout(()=>{
    PushNotification.getDeliveredNotifications(callBackTest);
    PushNotification.getScheduledLocalNotifications(callBackTest);
},10000);
*/
export const createNotificationChannel = () =>{
    PushNotification.createChannel(
        {
            channelId: "channel-cooltivar", // (required)
            channelName: "My channel", // (required)
            channelDescription: "A channel to categorise your notifications", // (optional) default: undefined.
            playSound: false, // (optional) default: true
            soundName: "default", // (optional) See `soundName` parameter of `localNotification` function
            importance: 4, // (optional) default: 4. Int value of the Android notification importance
            vibrate: true, // (optional) default: true. Creates the default vibration patten if true.
        },
        (created) => console.log(`Notification createChannel returned '${created}'`) // (optional) callback returns whether the channel was created, false means it already existed.
    );
};


export const createPushNotification = () => {
    PushNotification.localNotification({
        /* Android Only Properties */
        channelId: "channel-cooltivar",
        //id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
        ticker: "My Notification Ticker", // (optional)
        //autoCancel: true, // (optional) default: true
        largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
        smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
        bigText: "My big text that will be shown when notification is expanded", // (optional) default: "message" prop
        subText: "This is a subText", // (optional) default: none
        color: "red", // (optional) default: system default
        vibrate: true, // (optional) default: true
        vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
        tag: 'some_tag', // (optional) add tag to message
        group: "group", // (optional) add group to message
        ongoing: false, // (optional) set whether this is an "ongoing" notification
        title: "FORM ACTION  notifica normale",
        message: "messaggio notifica"
    });
};

export const createScheduledNotification = (title,description,date)=>{
    PushNotification.localNotificationSchedule({
        channelId: "channel-cooltivar",
        title: title,
        message: description, // (required)
        date: new Date(date) // in 60 secs
        //date: new Date(), // in 60 secs
    });
};
/*
PushNotification.getChannels(function (channel_ids) {
    console.log(channel_ids); // ['channel_id_1']
});*/
