export const E_INSERT_CULTIVATION_REQ = "INSERT_CULTIVATION_REQ";
export const E_INSERT_CULTIVATION_SUCCESS = "INSERT_CULTIVATION_SUCCESS";
export const E_INSERT_CULTIVATION_FAIL = "INSERT_CULTIVATION_FAIL";

export const E_UPDATE_CULTIVATION_REQ = "UPDATE_CULTIVATION_REQ";
export const E_UPDATE_CULTIVATION_SUCCESS = "UPDATE_CULTIVATION_SUCCESS";
export const E_UPDATE_CULTIVATION_FAIL = "UPDATE_CULTIVATION_FAIL";

export const E_DELETE_CULTIVATION_REQ = "DELETE_CULTIVATION_REQ";
export const E_DELETE_CULTIVATION_SUCCESS = "DELETE_CULTIVATION_SUCCESS";
export const E_DELETE_CULTIVATION_FAIL = "DELETE_CULTIVATION_FAIL";

export const E_FIND_CULTIVATION_REQ = "E_FIND_CULTIVATION_REQ";
export const E_FIND_CULTIVATION_SUCCESS = "E_FIND_CULTIVATION_SUCCESS";
export const E_FIND_CULTIVATION_FAIL = "E_FIND_CULTIVATION_FAIL";
