export const E_INSERT_FIELD_REQ = "INSERT_FIELD_REQ";
export const E_INSERT_FIELD_SUCCESS = "INSERT_FIELD_SUCCESS";
export const E_INSERT_FIELD_FAIL = "INSERT_FIELD_FAIL";

export const E_UPDATE_FIELD_REQ = "UPDATE_FIELD_REQ";
export const E_UPDATE_FIELD_SUCCESS = "UPDATE_FIELD_SUCCESS";
export const E_UPDATE_FIELD_FAIL = "UPDATE_FIELD_FAIL";

export const E_DELETE_FIELD_REQ = "DELETE_FIELD_REQ";
export const E_DELETE_FIELD_SUCCESS = "DELETE_FIELD_SUCCESS";
export const E_DELETE_FIELD_FAIL = "DELETE_FIELD_FAIL";

export const E_FIND_FIELD_REQ = "E_FIND_FIELD_REQ";
export const E_FIND_FIELD_SUCCESS = "E_FIND_FIELD_SUCCESS";
export const E_FIND_FIELD_FAIL = "E_FIND_FIELD_FAIL";


export const FieldEnum = {
    INSERT_REQ: E_INSERT_FIELD_REQ,
    INSERT_SUCCESS: E_INSERT_FIELD_SUCCESS,
    INSERT_FAIL: E_INSERT_FIELD_FAIL,

    UPDATE_REQ: E_UPDATE_FIELD_REQ,
    UPDATE_SUCCESS: E_UPDATE_FIELD_SUCCESS,
    UPDATE_FAIL: E_UPDATE_FIELD_FAIL,

    DELETE_REQ: E_DELETE_FIELD_REQ,
    DELETE_SUCCESS: E_DELETE_FIELD_SUCCESS,
    DELETE_FAIL: E_DELETE_FIELD_FAIL,

    FIND_REQ: E_FIND_FIELD_REQ,
    FIND_SUCCESS: E_FIND_FIELD_SUCCESS,
    FIND_FAIL: E_FIND_FIELD_FAIL,
};
