export const E_INSERT_OPERATION_REQ = "INSERT_OPERATION_REQ";
export const E_INSERT_OPERATION_SUCCESS = "INSERT_OPERATION_SUCCESS";
export const E_INSERT_OPERATION_FAIL = "INSERT_OPERATION_FAIL";

export const E_UPDATE_OPERATION_REQ = "UPDATE_OPERATION_REQ";
export const E_UPDATE_OPERATION_SUCCESS = "UPDATE_OPERATION_SUCCESS";
export const E_UPDATE_OPERATION_FAIL = "UPDATE_OPERATION_FAIL";

export const E_DELETE_OPERATION_REQ = "DELETE_OPERATION_REQ";
export const E_DELETE_OPERATION_SUCCESS = "DELETE_OPERATION_SUCCESS";
export const E_DELETE_OPERATION_FAIL = "DELETE_OPERATION_FAIL";

export const E_FIND_OPERATION_REQ = "E_FIND_OPERATION_REQ";
export const E_FIND_OPERATION_SUCCESS = "E_FIND_OPERATION_SUCCESS";
export const E_FIND_OPERATION_FAIL = "E_FIND_OPERATION_FAIL";
