import {
    E_DELETE_CULTIVATION_FAIL,
    E_DELETE_CULTIVATION_REQ,
    E_DELETE_CULTIVATION_SUCCESS,
    E_FIND_CULTIVATION_FAIL,
    E_FIND_CULTIVATION_REQ,
    E_FIND_CULTIVATION_SUCCESS,
    E_INSERT_CULTIVATION_FAIL,
    E_INSERT_CULTIVATION_REQ,
    E_INSERT_CULTIVATION_SUCCESS,
    E_UPDATE_CULTIVATION_FAIL,
    E_UPDATE_CULTIVATION_REQ,
    E_UPDATE_CULTIVATION_SUCCESS,
} from './CultivationEnum';

export const E_INSERT_OPERATION_REQ = "INSERT_OPERATION_REQ";
export const E_INSERT_OPERATION_SUCCESS = "INSERT_OPERATION_SUCCESS";
export const E_INSERT_OPERATION_FAIL = "INSERT_OPERATION_FAIL";

export const E_UPDATE_OPERATION_REQ = "UPDATE_OPERATION_REQ";
export const E_UPDATE_OPERATION_SUCCESS = "UPDATE_OPERATION_SUCCESS";
export const E_UPDATE_OPERATION_FAIL = "UPDATE_OPERATION_FAIL";

export const E_DELETE_OPERATION_REQ = "DELETE_OPERATION_REQ";
export const E_DELETE_OPERATION_SUCCESS = "DELETE_OPERATION_SUCCESS";
export const E_DELETE_OPERATION_FAIL = "DELETE_OPERATION_FAIL";

export const E_FIND_OPERATION_REQ = "E_FIND_OPERATION_REQ";
export const E_FIND_OPERATION_BY_CULTIVATION_REQ = "E_FIND_OPERATION_BY_CULTIVATION_REQ";
export const E_FIND_OPERATION_SUCCESS = "E_FIND_OPERATION_SUCCESS";
export const E_FIND_OPERATION_FAIL = "E_FIND_OPERATION_FAIL";

export const CultivActionEnum = {
    INSERT_REQ: E_INSERT_OPERATION_REQ,
    INSERT_SUCCESS: E_INSERT_OPERATION_SUCCESS,
    INSERT_FAIL: E_INSERT_OPERATION_FAIL,

    UPDATE_REQ: E_UPDATE_OPERATION_REQ,
    UPDATE_SUCCESS: E_UPDATE_OPERATION_SUCCESS,
    UPDATE_FAIL: E_UPDATE_OPERATION_FAIL,

    DELETE_REQ: E_DELETE_OPERATION_REQ,
    DELETE_SUCCESS: E_DELETE_OPERATION_SUCCESS,
    DELETE_FAIL: E_DELETE_OPERATION_FAIL,

    FIND_REQ: E_FIND_OPERATION_REQ,
    FIND_BY_CULTIVATION_REQ: E_FIND_OPERATION_BY_CULTIVATION_REQ,
    FIND_SUCCESS: E_FIND_OPERATION_SUCCESS,
    FIND_FAIL: E_FIND_OPERATION_FAIL,
};
